global:
  environment: dev
  namespace: snappaste

image:
  repository: ""   # set by pipeline
  tag: latest
  pullPolicy: Always

replicaCount: 1

port: 8000

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

env:
  DATABASE_URL: "postgresql://snappaste:snappaste@postgres:5432/snappaste"

ingress:
  enabled: true
  className: alb
  host: ""  # empty = path-based routing only (no domain needed)
